// Code generated by "stringer -type=Size -linecomment"; DO NOT EDIT.

package awssize

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[sizeNano-1]
	_ = x[sizeMicro-2]
	_ = x[sizeSmall-4]
	_ = x[sizeMedium-8]
	_ = x[sizeLarge-16]
	_ = x[sizeXlarge-32]
	_ = x[size2xLarge-64]
	_ = x[size3xLarge-96]
	_ = x[size4xLarge-128]
	_ = x[size8xLarge-256]
	_ = x[size9xLarge-288]
	_ = x[size10xLarge-320]
	_ = x[size12xLarge-384]
	_ = x[size16xLarge-512]
	_ = x[size18xLarge-576]
	_ = x[size24xLarge-768]
	_ = x[size32xLarge-1024]
	_ = x[size48xLarge-1536]
}

const _Size_name = "nanomicrosmallmediumlargexlarge2xlarge3xlarge4xlarge8xlarge9xlarge10xlarge12xlarge16xlarge18xlarge24xlarge32xlarge48xlarge"

var _Size_map = map[Size]string{
	1:    _Size_name[0:4],
	2:    _Size_name[4:9],
	4:    _Size_name[9:14],
	8:    _Size_name[14:20],
	16:   _Size_name[20:25],
	32:   _Size_name[25:31],
	64:   _Size_name[31:38],
	96:   _Size_name[38:45],
	128:  _Size_name[45:52],
	256:  _Size_name[52:59],
	288:  _Size_name[59:66],
	320:  _Size_name[66:74],
	384:  _Size_name[74:82],
	512:  _Size_name[82:90],
	576:  _Size_name[90:98],
	768:  _Size_name[98:106],
	1024: _Size_name[106:114],
	1536: _Size_name[114:122],
}

func (i Size) String() string {
	if str, ok := _Size_map[i]; ok {
		return str
	}
	return "Size(" + strconv.FormatInt(int64(i), 10) + ")"
}
